/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 edu.glb
*/

import { useGLTF } from '@react-three/drei'
import { editable } from '@theatre/r3f'

export function Edu(props) {
  const { nodes, materials } = useGLTF('./edu.glb')
  return (
    <group {...props} dispose={null}>
      <editable.mesh theatreKey="pedestal" geometry={nodes.pedestal.geometry} material={materials.Material} position={[0.01, 0.22, 0]} scale={[0.3, 0.26, 0.3]} />
      {/* <editable.mesh theatreKey="tongue" geometry={nodes.tongue.geometry} material={materials.DMU} position={[0.05, 2.38, 0.01]} rotation={[1.6, 0.02, 0.54]} scale={21.19} />
      <editable.mesh theatreKey="tail" geometry={nodes.tail.geometry} material={materials.DMU} position={[-0.19, 2.99, -0.1]} rotation={[1.6, 0.02, 0.54]} scale={21.19} />
      <editable.mesh theatreKey="shuriken" geometry={nodes.shuriken.geometry} material={materials.DMU} position={[-0.07, 1.91, -0.05]} rotation={[-1.53, -0.01, 2.6]} scale={-0.03} />
      <editable.mesh theatreKey="nose" geometry={nodes.nose.geometry} material={materials.DMU} position={[0.08, 2.64, 0.04]} rotation={[1.6, 0.02, 0.54]} scale={21.19} />
      <editable.mesh theatreKey="mouth" geometry={nodes.mouth.geometry} material={materials.DMU} position={[0.14, 2.54, -0.27]} rotation={[-1.53, -0.01, 2.6]} scale={-20.38} />
      <editable.mesh theatreKey="face" geometry={nodes.face.geometry} material={materials.DMU} position={[0.06, 2.58, 0.03]} rotation={[1.6, 0.02, 0.54]} scale={21.19} />
      <editable.mesh theatreKey="eye" geometry={nodes.eye.geometry} material={materials.DMU} position={[0.06, 2.65, 0.03]} rotation={[1.6, 0.02, 0.54]} scale={21.19} />
      <editable.mesh theatreKey="claw" geometry={nodes.claw.geometry} material={materials.DMU} position={[0.32, 2.31, 0.17]} rotation={[1.6, 0.02, 0.54]} scale={21.19} /> */}
      <editable.mesh theatreKey="one" geometry={nodes.one.geometry} material={materials.one} position={[-0.05, 2.63, 0.07]} scale={[0.35, 0.35, 0.57]} />
      <editable.mesh theatreKey="n" geometry={nodes.n.geometry} material={materials.deep_blue} position={[-0.31, 2.25, 0.03]} scale={[0.35, 0.35, 0.6]} />
      <editable.group theatreKey="r" position={[0.06, 2.51, 0.03]} scale={[0.35, 0.35, 0.62]}>
        <mesh geometry={nodes.Cube012.geometry} material={materials.deep_blue} />
        <mesh geometry={nodes.Cube012_1.geometry} material={materials.deep_blue} />
      </editable.group>
      <editable.mesh theatreKey="circle" geometry={nodes.circle.geometry} material={materials.deep_blue} position={[0.01, 2.41, 0.02]} rotation={[Math.PI / 2, 0, 0]} scale={[0.5, 0.06, 0.5]} />
      <editable.mesh theatreKey="cluster" geometry={nodes.cluster.geometry} material={materials.light_blue} position={[-0.26, 2.56, -0.03]} rotation={[0, 0, -0.73]} scale={[0.07, 0.07, 0.06]} />
      <editable.mesh theatreKey="circle_face" geometry={nodes.circle_face.geometry} material={materials.white} position={[0.01, 2.41, 0.02]} rotation={[Math.PI / 2, 0, 0]} scale={[0.5, 0.06, 0.5]} />
      <editable.mesh theatreKey="bottom_text" geometry={nodes.bottom_text.geometry} material={nodes.bottom_text.material} position={[0, 2.35, 0.02]} rotation={[Math.PI / 2, 0.85, 0]} scale={[0.07, 0.06, 0.07]} />
      <editable.mesh theatreKey="top_text" geometry={nodes.top_text.geometry} material={nodes.top_text.material} position={[0.01, 2.43, 0.02]} rotation={[-Math.PI / 2, -0.9, Math.PI]} scale={[0.07, 0.06, 0.07]} />
      <editable.mesh theatreKey="circle_backface" geometry={nodes.circle_backface.geometry} material={materials.white} position={[0.01, 2.41, 0.02]} rotation={[Math.PI / 2, 0, 0]} scale={[0.5, 0.06, 0.5]} />
    </group>
  )
}

useGLTF.preload('./edu.glb')
