/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 star.glb
*/

import { useGLTF } from '@react-three/drei'
import { editable } from '@theatre/r3f'
import starURL from './3Dmodels/star.glb'

export function Star(props) {
  const { nodes, materials } = useGLTF(starURL)
  return (
    <editable.group theatreKey="star" {...props} dispose={null}>
      <mesh geometry={nodes.star.geometry} material={materials.star} rotation={[Math.PI / 2, 0, 0.64]} scale={0.33} />
    </editable.group>
  )
}

useGLTF.preload('./star.glb')
