/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 laptop.glb
*/

import { useGLTF } from '@react-three/drei'
import { Html } from '@react-three/drei'


export function Laptop(props) {
  const { nodes, materials } = useGLTF('./laptop.glb')
  return (
    <group {...props} dispose={null}>
      <mesh geometry={nodes.base.geometry} material={materials.lap} position={[-0.96, 0.26, 1.13]} scale={[6, 0.18, 8.05]} />
      <mesh geometry={nodes.keyboard.geometry} material={materials.keyboard} position={[-2.5, 0.32, -4.81]} scale={[0.42, 0.09, 0.35]} />
      <mesh geometry={nodes.top.geometry} material={materials.lap} position={[6.47, 5.42, 1.15]} rotation={[-Math.PI, 0, -2.9]} scale={[0.18, 5.4, 8.05]} />
      <mesh geometry={nodes.screen.geometry} material={nodes.screen.material} position={[0.09, 5.66, 1.15]} rotation={[0, 0, -1.81]} scale={[4.58, 6.05, 7.38]} >
        <Html className="p-0 w-[100px] ml-[6px] mt-[-54px] h-[100px] bg-white" rotation-z={Math.PI / 2} rotation-x={Math.PI / 2} position={[0, 1.21, -0.09]} transform occlude>
        
        </Html>
      </mesh>
      <mesh geometry={nodes.touchpad.geometry} material={materials.touchpad} position={[-0.96, 0.28, 1.13]} scale={[6, 0.18, 8.05]} />
    </group>
  )
}

useGLTF.preload('./laptop.glb')
