/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.1.4 scroll.glb
Author: Pixel Life (https://sketchfab.com/pixellife)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/scroll-game-ready-asset-c1503d2292c74faebf83a5937646c1c7
Title: Scroll (game ready asset)
*/

import { editable } from '@theatre/r3f'

import { useGLTF } from '@react-three/drei'
import scrollURL from "./scroll.glb"

export function Scroll(props) {
  const { nodes, materials } = useGLTF(scrollURL)
  return (
    <editable.group theatreKey="scroll" {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh geometry={nodes.defaultMaterial.geometry} material={materials.DefaultMaterial} rotation={[Math.PI / 2, 0, 0]} />
      </group>
    </editable.group>
  )
}

useGLTF.preload('./scroll.glb')
